### ISSUE TITLE
win10 The system can not find the file specified

### ISSUE THREAD

**Issue by pengkaiwei** [konsti219/astro-starter#1]
The folder is a new empty folder。

This the logs ，tks!

[INFO] Downlaoding steamcmd...
[INFO] Downlaoding server files from steam...
[INFO] This will take a few minutes
error: NotFound: The system can not find the file specified。 (os error 2)
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at Object.opSync (deno:core/core.js:120:12)
    at opRun (deno:runtime/js/40_process.js:20:17)
    at Object.run (deno:runtime/js/40_process.js:104:17)
    at Starter.updateSteam (file://$deno$/bundle.js:14059:25)
    at async Starter.start (file://$deno$/bundle.js:13990:13)
    at async file://$deno$/bundle.js:14114:1

**Comment by konsti219** [comment]
Looks like it failed to unzip steamcmd using powershell. Try doing it manually.

**Comment by konsti219** [comment]
Please join the Astroneer Discord discord.gg/astroneer and ask in #self-host-talk.
